version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: university_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
    command: start-dev
    ports:
      - "8081:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data
    restart: unless-stopped

  backend:
    build: .
    depends_on:
      - mysql
      - keycloak
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mysql://mysql:3306/university_db
      - QUARKUS_DATASOURCE_USERNAME=root
      - QUARKUS_DATASOURCE_PASSWORD=root_password
      - QUARKUS_OIDC_AUTH_SERVER_URL=http://keycloak:8080/auth/realms/university
      - QUARKUS_OIDC_CLIENT_ID=university-backend
      - QUARKUS_OIDC_CREDENTIALS_SECRET=backend-secret
    restart: unless-stopped

volumes:
  mysql-data:
  keycloak-data:
